name: Deploy Express SDK

on:
  push:
    branches:
      - main
      - devops/*
    paths:
      - 'express/**'
  release:
    types: [created]

jobs:
  build-and-deploy-express:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: cd express && npm install

      - name: Run tests
        run: cd express && npm test

      - name: Generate JSDoc
        run: cd express && npm run jsdoc

      - name: Deploy JSDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./express/docs
          destination_dir: express/${{ github.event.release.tag_name }}
      
      - name: Generate Index Page 
        run: |
          echo "<html><body><h1>Express SDK Documentation</h1><ul>" > index.html
          for dir in $(ls express); do
            echo "<li><a href=\"express/$dir/index.html\">Version $dir</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html
      
      - name: Deploy Index Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          destination_dir: .

      # - name: Publish to npm
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: cd express && npm publish
